/*
 * Copyright (c) 2026. Oleksii Lykov.
 *
 * Licensed under the MIT License.
 * SPDX-License-Identifier: MIT
 */

package com.i2vision.agent

/**
 * A task request sent to an i2vision agent.
 * 
 * This is the primary input to agent execution. The request includes:
 * - A unique identifier for tracking and cancellation
 * - The task description in natural language
 * - Rich context from the client environment
 * - Optional configuration overrides for this specific request
 * 
 * Example usage:
 * ```kotlin
 * val request = AgentRequest(
 *     id = "req-123",
 *     task = "Refactor this function to use coroutines",
 *     context = AgentContext(
 *         workspaceRoot = "/path/to/project",
 *         currentFile = "/path/to/project/src/main/kotlin/MyClass.kt",
 *         sessionId = "session-456"
 *     ),
 *     config = AgentConfigOverrides(maxIterations = 5)
 * )
 * 
 * val response = agent.process(request)
 * ```
 * 
 * @property id Unique request identifier (generated by caller)
 * @property task The task description in natural language
 * @property context Execution context from the client environment
 * @property config Optional configuration overrides for this request only
 * @property timestamp Request timestamp (defaults to current time)
 */
data class AgentRequest(
    val id: String,
    val task: String,
    val context: AgentContext,
    val config: AgentConfigOverrides? = null,
    val timestamp: Long = System.currentTimeMillis()
) {
    /**
     * Check if this request has configuration overrides.
     */
    fun hasConfigOverrides(): Boolean = config != null
    
    /**
     * Get the effective configuration by applying overrides to the base config.
     * @param baseConfig The base configuration to apply overrides to
     * @return The effective configuration
     */
    fun getEffectiveConfig(baseConfig: AgentConfig): AgentConfig =
        config?.let { baseConfig.withOverrides(it) } ?: baseConfig
    
    companion object {
        /**
         * Generate a unique request ID.
         * Format: "req-" followed by timestamp and random suffix
         */
        fun generateId(): String =
            "req-${System.currentTimeMillis()}-${(Math.random() * 1000).toInt()}"
        
        /**
         * Create a simple request with minimal context.
         * Useful for testing and simple use cases.
         */
        fun simple(
            task: String,
            workspaceRoot: String,
            sessionId: String = "default-session"
        ): AgentRequest = AgentRequest(
            id = generateId(),
            task = task,
            context = AgentContext(
                workspaceRoot = workspaceRoot,
                sessionId = sessionId
            )
        )
    }
}
