/*
 * Copyright (c) 2026. Oleksii Lykov.
 *
 * Licensed under the MIT License.
 * SPDX-License-Identifier: MIT
 */

package com.i2vision.link

// ─── links.yaml models ──────────────────────────────────────────────────────────────

/** Granularity of a code-side target in a [LayerLink] */
enum class LinkTargetType { directory, file, symbol, range }

/** Distinguishes manually authored links from auto-discovered ones. */
enum class LinkSource { manual, discovered }

/** Type of relationship expressed by a link */
enum class LinkType { implements, calls, tests, documents, defines, uses, discovers }

/** Reference to a logic-layer artifact */
data class LogicRef(
    val module: String,
    val artifact: String,
    val ref: String
)

/** Reference to a code location */
data class CodeRef(
    val file: String,
    val line: Int? = null,
    val symbol: String? = null
)

/**
 * A cross-layer link connecting a logic artifact to code (or other layers).
 *
 * Example (new simplified YAML representation):
 * ```yaml
 * - id: rule:project-load-failure
 *   logic:
 *     module: core/orchestrator
 *     artifact: logic/business-rules.yaml
 *     ref: rule:project-load-failure
 *   code:
 *     file: core/orchestrator/src/main/kotlin/.../AgentOrchestrator.kt
 *     line: 269
 *     symbol: loadProject
 *   type: implements
 *   confidence: 0.95
 *   source: manual
 * ```
 */
data class LayerLink(
    /** Unique identifier for this link (simplified format like "rule:xyz") */
    val id: String,
    /** Logic-layer artifact reference (structured) */
    val logic: LogicRef,
    /** Code-side target */
    val code: CodeRef,
    /** Type of relationship */
    val type: LinkType = LinkType.implements,
    /** Confidence score 0.0-1.0 */
    val confidence: Double = 1.0,
    /** Optional human-readable note */
    val note: String? = null,
    /** Whether this link was authored manually or generated by DiscoveryPipeline */
    val source: LinkSource = LinkSource.manual
) {
    /** Legacy string-based logic reference for backward compatibility */
    val logicRefString: String get() = "${logic.module}/${logic.artifact}:${logic.ref}"

    fun endpointKeys(): List<String> = listOf(
        "logic:${logicRefString}",
        "code:${code.file}:${code.symbol ?: ""}"
    )
}

data class CodeTarget(
    val type: LinkTargetType,
    /** Path relative to project root */
    val path: String,
    /** Symbol name (only for type=symbol) */
    val symbol: String? = null,
    /** Line range (only for type=range); inclusive */
    val lineStart: Int? = null,
    val lineEnd: Int? = null
)

data class LinksFile(
    val version: String = "1",
    val links: List<LayerLink> = emptyList()
)
